export const GET_EMPLOYEE_LIST_REQUEST = "GET_EMPLOYEE_LIST_REQUEST";
export const GET_EMPLOYEE_LIST_RESPONSE = "GET_EMPLOYEE_LIST_RESPONSE";
export const GET_EMPLOYEE_REQUEST = "GET_EMPLOYEE_REQUEST";
export const GET_EMPLOYEE_RESPONSE = "GET_EMPLOYEE_RESPONSE";
export const GET_EMPLOYEEID_RESPONSE = "GET_EMPLOYEE_RESPONSEID";
export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE_RESPONSE = "DELETE_EMPLOYEE_RESPONSE";
export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_RESPONSE = "ADD_EMPLOYEE_RESPONSE";
export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE_RESPONSE = "UPDATE_EMPLOYEE_RESPONSE";

export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";